updated docker

diff --git a/backend/userservice/Dockerfile.dev b/backend/userservice/Dockerfile.dev
--- a/backend/userservice/Dockerfile.dev
+++ b/backend/userservice/Dockerfile.dev
@@ -4,7 +4,7 @@ FROM python:3.12-slim
 # Set the working directory in the container
 WORKDIR /usr/src/app
 
-# Install system dependencies (build-essential and libpq-dev are often needed for installing dependencies)
+# Install system dependencies (only if you need them)
 RUN apt-get update && apt-get install -y \
     build-essential \
     libpq-dev \
@@ -19,6 +19,11 @@ RUN pip install --upgrade pip && \
 
 # Copy the rest of the application code
 COPY . .
+
+# Make the run_migrations.sh script executable and run it
+RUN chmod +x run_migrations.sh && \
+    ./run_migrations.sh || true
+# Ensure the migration script exits with failure if theres an issue
 
 # Expose the port your app runs on
 EXPOSE 8000
